### ISSUE TITLE
(1) Use Jbuilder to create a JSON endpoint for data visualizations

### ISSUE THREAD

**Issue by yagihashib** [yagihashib/tc359_rails_final#3]

**Comment by yagihashib** [comment]
@chrisvfritz Finished. I think jbuilder was already set up for my model from the scaffold generation?

**Comment by chrisvfritz** [comment]
Since we don't need to share [all of this information](https://github.com/yagihashib/tc359_rails_final/blob/master/app/views/nbaplayers/index.json.jbuilder#L2) for the visualization, let's restrict the JSON to the fields we actually want to use there.

**Comment by yagihashib** [comment]
@chrisvfritz Ok, I've removed the :id attribute from the jsonbuilder files.

**Comment by chrisvfritz** [comment]
:+1: Looks good.
